sonar.projectName=rust-playground
sonar.sources=crates
sonar.tests=crates
sonar.test.inclusions=**/*test*.rs,**/tests/**/*.rs
sonar.exclusions=target/**,logs/**,outputs/**
sonar.rust.lcov.reportPaths=target/coverage/lcov.info
sonar.sourceEncoding=UTF-8

